[
    {
        "content": "<p>It seems like the last two attempts to merge something had their ci cancelled? <a href=\"https://github.com/leanprover-community/mathlib/actions/workflows/bors.yml?query=branch%3Astaging\">https://github.com/leanprover-community/mathlib/actions/workflows/bors.yml?query=branch%3Astaging</a></p>",
        "id": 312503018,
        "sender_full_name": "Ruben Van de Velde",
        "timestamp": 1669573107
    },
    {
        "content": "<p>bors keeps misreporting that Ci runs failed linting when in fact they failed building. <a href=\"https://github.com/leanprover-community/mathlib/pull/17055#issuecomment-1379515701\">Here's one example</a>. Why do you think this is happening?</p>",
        "id": 320802778,
        "sender_full_name": "Yaël Dillies",
        "timestamp": 1673473296
    },
    {
        "content": "<p>I think you would do better to report that upstream to bors</p>",
        "id": 320806195,
        "sender_full_name": "Eric Wieser",
        "timestamp": 1673474646
    },
    {
        "content": "<p>It seems like the latest bors run failed (<a href=\"https://github.com/leanprover-community/mathlib4/actions/runs/6160617263/job/16717992280\">https://github.com/leanprover-community/mathlib4/actions/runs/6160617263/job/16717992280</a>), but it's not starting any new ones</p>",
        "id": 390541696,
        "sender_full_name": "Ruben Van de Velde",
        "timestamp": 1694531831
    },
    {
        "content": "<p>Mario's and Scott's heroic efforts on improving CI and caching caused some hiccups. But hopefully everything is back on track (soon).</p>",
        "id": 390542853,
        "sender_full_name": "Johan Commelin",
        "timestamp": 1694532161
    },
    {
        "content": "<p>that error looks like a std bump issue</p>",
        "id": 390543884,
        "sender_full_name": "Mario Carneiro",
        "timestamp": 1694532418
    },
    {
        "content": "<p>The error is from <a href=\"https://github.com/leanprover-community/mathlib4/pull/3464\">#3464</a></p>",
        "id": 390544162,
        "sender_full_name": "Ruben Van de Velde",
        "timestamp": 1694532489
    },
    {
        "content": "<p>FYI I'm done for the day re: fixing the cache issues, there are now threads for <span class=\"user-mention silent\" data-user-id=\"315577\">Mac Malone</span> and <span class=\"user-mention silent\" data-user-id=\"128280\">Wojciech Nawrocki</span> to follow up on</p>",
        "id": 390544285,
        "sender_full_name": "Mario Carneiro",
        "timestamp": 1694532522
    },
    {
        "content": "<p>I am not sure if this is relevant, but my PR <a href=\"https://github.com/leanprover-community/mathlib4/pull/7075\">#7075</a> was in the queue and really  acquired a merge conflict.  I have resolved the conflict and CI is linting it.</p>",
        "id": 390547092,
        "sender_full_name": "Damiano Testa",
        "timestamp": 1694533308
    },
    {
        "content": "<p><a href=\"https://github.com/leanprover-community/mathlib4/pull/7075\">#7075</a> passed CI after the merge conflict, but is no longer on the bors queue: can someone put it there again, please?  Thanks!</p>",
        "id": 390555678,
        "sender_full_name": "Damiano Testa",
        "timestamp": 1694535956
    },
    {
        "content": "<p>Would be nice if one of the maintainers could go through <a href=\"https://github.com/leanprover-community/mathlib4/pulls?q=is%3Aopen+is%3Apr+label%3Aready-to-merge\">https://github.com/leanprover-community/mathlib4/pulls?q=is%3Aopen+is%3Apr+label%3Aready-to-merge</a> and put them on the queue again</p>",
        "id": 390582125,
        "sender_full_name": "Ruben Van de Velde",
        "timestamp": 1694546418
    },
    {
        "content": "<p>We should have a triage-like bot for this (that reposts a link to all prs that have been marked ready to merge for 24h say). Or just find a way to stop bors forgetting about such prs.</p>",
        "id": 390589587,
        "sender_full_name": "Alex J. Best",
        "timestamp": 1694549692
    },
    {
        "content": "<p>I think I’ve told bors to retry on each of them (with the exception of <a href=\"https://github.com/leanprover-community/mathlib4/pull/7099\">#7099</a> which was causing the failures IIUC), let me know if I missed any</p>",
        "id": 390603736,
        "sender_full_name": "Anatole Dedecker",
        "timestamp": 1694556097
    }
]