[
    {
        "content": "<p>Trying to get <a href=\"https://gitlab.com/ilds/aml-lean/MatchingLogic/\">this repository</a> to work, I get the following error:</p>\n<div class=\"codehilite\" data-code-language=\"Lean\"><pre><span></span><code><span class=\"n\">Lean</span> <span class=\"o\">(</span><span class=\"n\">version</span> <span class=\"mi\">4</span><span class=\"bp\">.</span><span class=\"mi\">0</span><span class=\"bp\">.</span><span class=\"mi\">0</span><span class=\"bp\">-</span><span class=\"n\">nightly</span><span class=\"bp\">-</span><span class=\"mi\">2023</span><span class=\"bp\">-</span><span class=\"mi\">03</span><span class=\"bp\">-</span><span class=\"mi\">09</span><span class=\"o\">,</span> <span class=\"n\">commit</span> <span class=\"mi\">0</span><span class=\"n\">cc9d7a43de7</span><span class=\"o\">,</span> <span class=\"n\">Release</span><span class=\"o\">)</span>\n<span class=\"n\">PANIC</span> <span class=\"n\">at</span> <span class=\"n\">_private.Lean.Meta.Match.MatchEqs.0.Lean.Meta.Match.SimpH.substRHS</span> <span class=\"n\">Lean.Meta.Match.MatchEqs</span><span class=\"o\">:</span><span class=\"mi\">167</span><span class=\"o\">:</span><span class=\"mi\">2</span><span class=\"o\">:</span> <span class=\"n\">assertion</span> <span class=\"n\">violation</span><span class=\"o\">:</span> <span class=\"o\">(</span> <span class=\"n\">__do_lift._</span><span class=\"bp\">@.</span><span class=\"n\">Lean.Meta.Match.MatchEqs._hyg.2199.0</span> <span class=\"o\">)</span><span class=\"bp\">.</span><span class=\"n\">xs.contains</span> <span class=\"n\">rhs</span>\n</code></pre></div>\n<p>I am not sure what this error means, it looks like there is a error generated by the Lean library, rather than the code in the library I downloaded. Is this right?</p>",
        "id": 357312999,
        "sender_full_name": "Bolton Bailey",
        "timestamp": 1683729161
    },
    {
        "content": "<p>Yes, the panic occurs at the line <code>assert! (‚Üê get).xs.contains rhs</code>, line 167 of <code>Lean.Meta.Match.MatchEqs</code> of the Lean 4 repo.</p>",
        "id": 357314652,
        "sender_full_name": "Floris van Doorn",
        "timestamp": 1683729429
    },
    {
        "content": "<p>Does this mean a bug report needs to be filed with the library then? (Or perhaps I should upgrade lean and see if that fixes it)?</p>",
        "id": 357315017,
        "sender_full_name": "Bolton Bailey",
        "timestamp": 1683729493
    },
    {
        "content": "<p>Probably, but it would be helpful to see what piece of code is causing it. Maybe the repo is doing something clearly illegal and the problem is only that you get a panic instead of a nice error message.<br>\nIt's looks like it's related to making equation lemmas for <code>match</code> expressions.</p>",
        "id": 357315728,
        "sender_full_name": "Floris van Doorn",
        "timestamp": 1683729603
    },
    {
        "content": "<p>The issue is, it's a big project and I don't know how to locate what part of it is calling this assertion. I guess it's some call to <code>simp</code>? What is <code>SimpH</code>?</p>",
        "id": 357336043,
        "sender_full_name": "Bolton Bailey",
        "timestamp": 1683733357
    },
    {
        "content": "<p>It seems the error is in <code>MatchingLogic/Proof.lean</code>. It's quite annoying the error message doesn't tell us which declaration or command the PANIC occurred in. You could probably localize it by doing a binary search by moving #exit around in the file in VSCode, however lame that sounds. :-)</p>",
        "id": 357515063,
        "sender_full_name": "Kim Liesinger",
        "timestamp": 1683795614
    }
]